name: Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install Jekyll and Bundler
        run: |
          gem install jekyll -v 4.3.3
          gem install bundler

      - name: Build Site
        run: |
          bundle install
          bundle exec jekyll build

      - name: Unzip webHelpMG2-all.zip
        run: |
          unzip -o _site/docs/webHelpMG2-all.zip -d _site/docs/

      - name: Upload _site directory
        uses: actions/upload-artifact@v4.3.5
        with:
          name: site
          path: _site
          if-no-files-found: error
          retention-days: 7
          compression-level: '6'
          overwrite: true

      - name: Update package list and install rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: _site
